# Generated by Django 5.2.6 on 2025-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(default="en", max_length=8),
        ),
    ]
