# Generated by Django 5.2.6 on 2025-09-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitlog",
            name="habit",
        ),
        migrations.RemoveConstraint(
            model_name="habit",
            name="habit_duration_1_120",
        ),
        migrations.RemoveConstraint(
            model_name="habit",
            name="habit_periodicity_1_7",
        ),
        migrations.RemoveConstraint(
            model_name="habit",
            name="habit_no_reward_and_related",
        ),
        migrations.RemoveConstraint(
            model_name="habit",
            name="habit_pleasant_has_no_reward_or_related",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="duration_seconds",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="is_pleasant",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="place",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="related_habit",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="reward",
        ),
        migrations.DeleteModel(
            name="HabitLog",
        ),
    ]
